diplom/diplom/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index,),
    path('diplom/', include('diplom_spo.urls', namespace='diplom_spo')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

diplom/diplom_spo/urls.py
from django.urls import path
from . import views

app_name = 'diplom_spo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.diplom_detail, name='detail'),
    path('<int:pk>/edit/', views.diplom_edit, name='edit'),
    path('create/', views.diplom_create, name='create'),
]

diplom/users/urls.py
from django.contrib.auth.views import (LogoutView,
                                       LoginView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/',
         views.SignUp.as_view(template_name='users/signup.html'),
         name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'), name='login'),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView.as_view(
          #    template_name='users/password_reset_form.html'
             ),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
          #    template_name='users/password_reset_done.html'
             ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
          #    template_name='users/password_reset_confirm.html'
             ),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
               #  template_name='users/password_reset_complete.html'
                ),
         name='password_reset_complete'),
]

diplom/diplom_spo/models.py
from django.db import models


class Diplom(models.Model):
    org_name = models.CharField(verbose_name="Название образовательной организации",
                                help_text="Введите навзвание образовательной организации",
                                max_length=200,
                                )
    qualification = models.CharField(max_length=100,
                                     verbose_name="Квалификация",
                                     help_text="Напишите квалификацию",
                                    )
    ser_number = models.CharField(max_length=15,
                                  verbose_name="Номер серии",
                                  help_text="Введите номер серии",
                                  )
    reg_number = models.CharField(max_length=10,
                                  verbose_name="Регистрационный номер",
                                  help_text="Введите регистрационный номер",
                                  )
    grant_date = models.DateField(verbose_name="Дата выдачи",
                                  help_text='Введите дату выдачи',
                                  )
    student_name = models.CharField(max_length=200,
                                    verbose_name="ФИО",
                                    help_text="ФИО",
                                    )
    speciality = models.CharField(max_length=100,
                                  verbose_name="Специальность",
                                  help_text="Введите специальность",
                                  )
    supervisor = models.CharField(max_length=200,
                                  verbose_name="Руководитель",
                                  help_text="Введите ФИО руководителя",
                                  )
    chairman = models.CharField(max_length=200,
                                verbose_name="Председатель ЭКЗ комиссии",
                                help_text="Введите ФИО председатель",
                                )
    year = models.DateField(verbose_name="Дата решения",
                            help_text="Введите дату решения",
                            )
    copy = models.ImageField(verbose_name="Копия диплома",
                             help_text="Вставьте копию диплома",
                             upload_to='diplomas/',
                             null=False,
                             blank=False,
                             )

    class Meta:
        ordering = ('year',)
        verbose_name = 'Диплом'
        verbose_name_plural = 'Дипломы'

    def __str__(self):
        return f"{self.student_name} - ({self.year})"

diplom/users/models.py
from django.db import models

# Create your models here.

diplom/diplom_spo/forms.py
from django import forms

from .models import Diplom


class DiplomForm(forms.ModelForm):
    class Meta:
        model = Diplom
        fields = ('org_name', 'qualification', 'ser_number', 'reg_number',
                  'grant_date', 'student_name', 'speciality', 'chairman',
                  'supervisor', 'year', 'copy', )

diplom/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email') 

diplom/diplom_spo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls.base import reverse
from django.core.paginator import Paginator
from .models import Diplom
from .forms import DiplomForm

MAX_DIPLOM_ON_PAGE = 5

# def index(request):
#     return HttpResponse('Диплом ПОКАЖИ!!!!!')


def index(request):
    diploms = Diplom.objects.all()
    paginator = Paginator(diploms, MAX_DIPLOM_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'diploms': diploms,
        'page_obj': page_obj,
    }
    return render(request, 'diplom/diplom_list.html', context)


def diplom_edit(request, pk):
    diplom = get_object_or_404(Diplom, pk=pk)
    if request.method == 'POST':
        form = DiplomForm(request.POST or None, files=request.FILES or None,
                          instance=diplom)
        if form.is_valid():
            form.save()
            return redirect(reverse('diplom_spo:index'))
    else:
        form = DiplomForm(instance=diplom)
    return render(request, 'includes/diplom_form.html', {'form': form})


def diplom_detail(request, pk):
    diplom = get_object_or_404(Diplom, pk=pk)
    context = {
        'diplom': diplom
    }
    return render(request, 'diplom/diplom_detail.html', context)


def diplom_create(request):
    if request.method == 'POST':
        form = DiplomForm(request.POST, files=request.FILES,)
        if form.is_valid():
            form.save()
            return redirect(reverse('diplom_spo:index'))
    else:
        form = DiplomForm()
    return render(request, 'includes/diplom_form.html', {'form': form})


# def diplom_create(request):
#     form = DiplomForm(
#         request.POST or None,
#         files=request.FILES or None
#     )
#     if form.is_valid():
#         form.save()  # сохраняем паспорт в базу данных
#         return redirect(reverse('diplom:index'))  # перенаправляем на главную страницу
#     return render(request, 'diplom/diplom_create.html', {'form': form})

diplom/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('diplom_spo:index')
    template_name = 'users/signup.html'

diplom/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        The title is not existed
      {% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    {% block content %}
      Информация не найдена
    {% endblock%}
    {% include "includes/footer.html" %}       
  </body>
</html>

diplom/templates/diplom/diplom_create.html
{% extends "base.html" %}
{% block title %}
  {% if not is_edit %}
    Создание записи о дипломе
  {% else %}
    Редактирование записи о дипломе
  {% endif %}
{% endblock %}
{% block content %}
  {% if is_edit %}
    {% with form_title='Редактирование записи о дипломе' form_url='diplom_spo:edit' url_param=diplom_id button_name='Редактировать' has_link_to_reset_password=False %}
      {% include 'templates/includes/diplom_form.html' %}
    {% endwith %}
  {% else %}
    {% with form_title='Создание записи о дипломе' form_url='diplom_spo:create' button_name='Создать запись' has_link_to_reset_password=False %}
      {% include 'templates/includes/diplom_form.html' %}
    {% endwith %}
  {% endif %}
{% endblock %}

diplom/templates/diplom/diplom_detail.html
{% extends "base.html" %}
{% block title %}
    Диплом: {{ diplom.student_name }}
{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Организация: {{ diplom.org_name }}
                </li>
                <li class="list-group-item">
                    Квалификация: {{ diplom.qualification }}
                </li>
                <li class="list-group-item">
                    Номер серии: {{ diplom.ser_number }}
                </li>
                <li class="list-group-item">
                    Регистрационный номер: {{ diplom.reg_number }}
                </li>
                <li class="list-group-item">
                    Дата выдачи: {{ diplom.grant_date }}
                </li>
                <li class="list-group-item">
                    ФИО студента: {{ diplom.student_name }}
                </li>
                <li class="list-group-item">
                    Специальность: {{ diplom.speciality }}
                </li>
                <li class="list-group-item">
                    Руководитель: {{ diplom.supervisor }}
                </li>
                <li class="list-group-item">
                    Председатель экзаменационной комиссии: {{ diplom.chairman }}
                </li>
                <li class="list-group-item">
                    Дата решения: {{ diplom.year }}
                </li>
                <li class="list-group-item">
                    Копия диплома: {{ diplom.copy }}
                </li>
            </ul>
        </div> 
        <div class="col-md-5 offset-md-5">
            <a class="btn btn-primary" href="{% url 'diplom_spo:edit' diplom.pk %}">
                Редактировать
            </a>
        </div>
    </div>     
{% endblock %}

diplom/templates/diplom/diplom_list.html
{% extends 'base.html' %}
{% block title %}
Дипломы
{% endblock %}
{% block content %}
<div>
    <!-- Таблица со списком дипломов -->
    <table class="table table-bordered border-primary">
        <thead>
            <tr>
                <th>Название образовательной организации</th>
                <th>Специальность</th>
                <th>Дата решения о выдаче</th>
                <th>Действия</th>
            </tr>
        </thead>
            <tbody>
                {% for diplom in page_obj %}
                    <tr>
                        <td>
                            <a href="{% url 'diplom_spo:detail' diplom.pk %}">{{ diplom.org_name }}</a>
                        </td>
                        <td>{{ diplom.speciality }}</td>
                        <td>{{ diplom.year }}</td>
                        <td>
                            <!-- Ссылка на редактирование -->
                            <a href="{% url 'diplom_spo:edit' diplom.pk %}">Редактировать</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Нет данных для отображения.</td>
                    </tr>
                {% endfor %}
            </tbody>
    </table>
    {% include 'includes/paginator.html' %}
</div>
{% endblock %}

diplom/templates/includes/diplom_form.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактирование записи о дипломе
  {% else %}
    Создать запись о дипломе
  {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-10 p-5">
      <div class="card">
        <div class="card-header">
          Добавить запись о дипломе
        </div>
        <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
        <form enctype="multipart/form-data" method="post"
        {% if action_url %}
        action="{% url action_url %}"
        {% endif %}
        >
          {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            {% with field=form.org_name %}
              {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-6">
            {% with field=form.speciality %}
              {% include 'includes/field.html' %}
            {% endwith %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            {% with field=form.qualification %}
            {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-4">
            {% with field=form.ser_number %}
            {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-4">
            {% with field=form.student_name %}
              {% include 'includes/field.html' %}
            {% endwith %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            {% with field=form.supervisor %}
            {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-4">
            {% with field=form.reg_number %}
            {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-4">
            {% with field=form.chairman %}
            {% include 'includes/field.html' %}
            {% endwith %}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            {% with field=form.grant_date %}
            {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-4">
            {% with field=form.year %}
              {% include 'includes/field.html' %}
            {% endwith %}
          </div>
          <div class="col-md-4">
            {% with field=form.copy %}
              {% include 'includes/field.html' %}
            {% endwith %}
          </div>
        </div>
        <div class="col-md-5 offset-md-5">
          <button type="submit" class="btn btn-primary">
            Создать документ
          </button>
          <a href="{% url 'diplom_spo:index' %}">Отмена</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

diplom/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© {{2025}} Copyright
      <p><span style="color:red">Dip</span>lom</p> 
    </div>    
  </footer>

diplom/templates/includes/header.html
{% load static %}
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'diplom_spo:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Dip</span>lom
        </a>
        <ul class="nav nav-pills"> 
          {% with request.resolver_match.view_name as view_name %}
            {% if user.is_authenticated %} 
          <li class="nav-item">  
            <a class="nav-link
            {% if view_name == 'diplom_spo:create' %}
            active
            {% endif %}" 
            href="{% url 'diplom_spo:create' %}">Новый документ</a> 
          </li> 
          <li class="nav-item">  
            <a class="nav-link link-light
            {% if view_name == 'users:password_change' %}
            active
            {% endif %}"
            href="{% url 'users:password_change' %}">Изменить пароль</a> 
          </li> 
          <li class="nav-item">  
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a> 
          </li> 
          <li> 
            Пользователь: {{ user.username }} 
          </li> 
          {% else %} 
          <li class="nav-item">  
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a> 
          </li> 
          <li class="nav-item">  
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a> 
          </li> 
          {% endif %} 
          {% endwith %}
          </ul>        
      </div>
    </nav>      
  </header>

diplom/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %} 
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет --> 
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

diplom/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_change' %}">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

diplom/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

diplom/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_reset' %}">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
      </div>
{% endblock %}

diplom/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="{% url 'users:password_reset' %}">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  {% csrf_token %}  
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
{% endblock %}

diplom/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %} 
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
              {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label> 
              {{ field|addclass:'form-control' }} 
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
              Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 